### ISSUE TITLE
hello, srv query errror

### ISSUE THREAD

**Issue by dly667** [metaregistrar/php-dns-client#11]
`$dns = new \DNSParser\dnsProtocol();
        $dns->setServer('47.111.151.0');
        $dns->setPort(8600);
        $result = $dns->Query('top3unlock_server.service.consul','SRV');`

![image](https://user-images.githubusercontent.com/26707226/132628085-0c525d1f-e883-4184-a360-abf14cc8d978.png)

**Comment by metaregistrar** [comment]
Unable to reproduce this issue
