### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ikovalyov** [metaregistrar/php-dns-client#2]
Hi.
Can you please give us more info about project license type? composer.json says "license": "proprietary".
Thanks,

**Comment by metaregistrar** [comment]
Hello

License is GNU

https://github.com/metaregistrar/php-epp-client/blob/master/LICENSE.md

Vriendelijke groeten/kind regards,

Ewout de Graaf
Metaregistrar

2016-06-27 14:21 GMT+02:00 ikovalyov notifications@github.com:

**Comment by ikovalyov** [comment]
ok, thanks.
