### ISSUE TITLE
error fsockopen command

### ISSUE THREAD

**Issue by Muraveiko** [metaregistrar/php-dns-client#3]
php-dns-client / DNS / dnsProtocol.php 
line 100 
timeout must be 5 . 
skipped 
&errno - 3
&errstr - 4

**Comment by Muraveiko** [comment]
create pull request

**Comment by metaregistrar** [comment]
Thanks for your contribution, i have merged your pull request into the main
branch.

Vriendelijke groeten/kind regards,

Ewout de Graaf
Metaregistrar

2016-08-21 7:37 GMT+02:00 Muraveiko Oleg U. notifications@github.com:
